# Generated by Django 3.0.4 on 2020-03-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='user',
        ),
    ]
