# Generated by Django 3.0.4 on 2020-03-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_auto_20200321_0631"),
    ]

    operations = [
        migrations.AlterModelOptions(name="board", options={"ordering": ["id"]},),
    ]
