# Generated by Django 3.0.6 on 2020-05-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0010_auto_20200517_0826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board", name="name", field=models.CharField(max_length=50),
        ),
    ]
