# Generated by Django 3.0.4 on 2020-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_auto_20200329_0919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="description", field=models.TextField(blank=True),
        ),
    ]
