# Generated by Django 3.0.4 on 2020-05-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0007_label"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("name", "board"), name="unique_name_board"
            ),
        ),
    ]
