# Generated by Django 3.0.4 on 2020-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0008_auto_20200510_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(related_name="tasks", to="boards.Label"),
        ),
    ]
